[project]
name = "anndata_pango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yangxin-Zhang", email = "910858193@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
anndata-pango = "anndata_pango:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
